server:
  port: 8080
  servlet:
    context-path: /demo
  shutdown: graceful

spring:
  profiles:
    active: prod
  application:
    name: demo-services
  lifecycle:
    timeout-per-shutdown-phase: 30s
  datasource:
    max:
      connection:
        pool:
          size: 100
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://chrissqldemoserver.database.windows.net:1433;database=demo_db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: demo_sa@chrissqldemoserver
    password: Password@1

  flyway:
    driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://chrissqldemoserver.database.windows.net:1433;database=demo_db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    user: demo_sa@chrissqldemoserver
    password: Password@1
  rabbitmq:
    host: amqps://lwbhtyvo:Ni7ydb_NEX-cYcpe11Dur1N6u9eZaPsm@[2001:db8:85a3:8d3:1319:8a2e:370:7348]/lwbhtyvo

  mail:
    default-encoding: UTF-8
    host: smtp.mailtrap.io
    username: 4128011bd36b9e
    password: d1373a16c84103
    port: 2525
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false

email:
  defaults:
    sender: support@demo.com
  subject:
    user-deactivation: You have been deactivated on Demo Platform
    user-verification: Verify your account on Demo Platform
  templates:
    user-deactivation: user-deactivation-template
    user-verification: user-verification-template

app:
  security:
    password-strength: 12

logging:
  level:
    org:
      springframework: INFO
