server:
  port: 8080
  servlet:
    context-path: /demo
  shutdown: graceful

spring:
  profiles:
    active: dev
  application:
    name: demo-services
  lifecycle:
    timeout-per-shutdown-phase: 30s
  datasource:
    max:
      connection:
        pool:
          size: 100
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://127.0.0.1;databaseName=demo_db;portNumber=1433
    username: sa
    password: Password@1

  flyway:
    user: sa
    password: Password@1
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  mail:
    default-encoding: UTF-8
    host: smtp.mailtrap.io
    username: ba82994703feaa
    password: ea2c03a9a0d824
    port: 2525
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false

email:
  defaults:
    sender: support@demo.com
  subject:
    user-deactivation: You have been deactivated on Demo Platform
    user-verification: Verify your account on Demo Platform
  templates:
    user-deactivation: user-deactivation-template
    user-verification: user-verification-template

app:
  security:
    password-strength: 12

logging:
  level:
    org:
      springframework: INFO
